# ArgoCD Project for API Gateway - SECURITY BOUNDARY AND ORGANIZATION UNIT
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: api-gateway # Project identifier
  namespace: argocd # Lives in ArgoCD namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: API Gateway project with Envoy Gateway, Backend and Frontend

  # Source repositories
  sourceRepos:
    - "https://github.com/angelenriquep/infra-k3s"
    - "*" # Allow all repositories - SECURITY RISK!

  # Destination clusters and namespaces - where the apps can deploy
  destinations:
    - namespace: "development"
      server: https://kubernetes.default.svc
    - namespace: "production"
      server: https://kubernetes.default.svc
    - namespace: "envoy-gateway-system"
      server: https://kubernetes.default.svc
    - namespace: "default"
      server: https://kubernetes.default.svc

  # Cluster resource allow list
  clusterResourceWhitelist:
    - group: "gateway.networking.k8s.io"
      kind: "*"
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
    - group: ""
      kind: "Namespace"

  # Namespace resource allow list
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "*" # All resource types in these groups
    - group: ""
      kind: "*" # All resource types in these groups
    - group: "gateway.networking.k8s.io"
      kind: "*" # All resource types in these groups
    - group: "networking.k8s.io"
      kind: "*" # All resource types in these groups

  # Roles for RBAC
  roles:
    - name: admin
      description: Admin access to API Gateway project
      policies:
        - p, proj:api-gateway:admin, applications, *, api-gateway/*, allow
        - p, proj:api-gateway:admin, repositories, *, *, allow
      groups:
        - api-gateway-admins

    - name: developer
      description: Developer access to development environment
      policies:
        - p, proj:api-gateway:developer, applications, get, api-gateway/api-gateway-dev, allow
        - p, proj:api-gateway:developer, applications, sync, api-gateway/api-gateway-dev, allow
      groups:
        - api-gateway-developers
