# YAML Lint Configuration
extends: default

rules:
  # Line length
  line-length:
    max: 120
    level: warning

  # Indentation
  indentation:
    spaces: 2

  # Comments
  comments:
    min-spaces-from-content: 1

  # Document separators
  document-start:
    present: true

  # Truthy values
  truthy:
    allowed-values: ["true", "false", "on", "off"]

  # Brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Key duplicates
  key-duplicates: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

ignore: |
  .github/
  experimental/
