---
# NodePort Service for ArgoCD Server - External Access - UI
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-nodeport
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
      nodePort: 32080 # ArgoCD será accesible en el puerto 32080
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32081 # Puerto para gRPC/CLI
  selector:
    app.kubernetes.io/name: argocd-server
