---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: migration-target
  namespace: default
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "128MB"
      effective_cache_size: "512MB"
      max_replication_slots: "10"
      max_wal_senders: "10"
      max_logical_replication_workers: "4"
      shared_preload_libraries: ""

  storage:
    size: 1Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 500Mi
