apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: migration-target-scheduled-backup
  namespace: default
spec:
  schedule: "0 0 2 * * *" # Daily at 2 AM UTC
  backupOwnerReference: self
  cluster:
    name: migration-target
  method: barmanObjectStore
  target: primary
