# ArgoCD Application for API Gateway Development Environment
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-dev
  namespace: argocd
  labels:
    environment: development
    project: api-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: api-gateway

  source:
    repoURL: https://github.com/tu-usuario/infra-k3s # Cambia por tu repo
    targetRevision: main # o develop branch para dev
    path: api-gateway/overlays/development

  destination:
    server: https://kubernetes.default.svc
    namespace: development

  syncPolicy:
    automated:
      prune: true # Elimina recursos que ya no están en Git
      selfHeal: true # Auto-corrige drift del cluster
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true # Crea namespace si no existe
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks personalizados
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas # Ignora cambios manuales en replicas (HPA)

  # Notificaciones y hooks
  revisionHistoryLimit: 10
