apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Application workloads
  - api-gateway.yaml
  # Infrastructure tools
  - cert-manager.yaml
  - reloader.yaml
  - argo-rollouts.yaml
  - kyverno.yaml
labels:
  - pairs:
      managed-by: argocd
      component: gitops
commonAnnotations:
  argocd.argoproj.io/managed: "true"
