apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: DB_HOST
              value: "dev-api-gateway-postgres.default.svc.cluster.local"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-gateway-app.dev-api-gateway-postgres.credentials.postgresql.acid.zalan.do
                  key: password
