apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-nodeport
  namespace: envoy-gateway-system
spec:
  ports:
    - name: http
      port: 80
      targetPort: 10080
      nodePort: 30081 # Different port to avoid conflict
