apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
    - backend/backend-api.yaml
    - backend/network-policy.yaml
    - cluster/minio/minio-deployment.yaml
    - cluster/minio/minio-init-job.yaml

commonAnnotations:
    managed-by: kustomize
